[build]
  publish = "."  # Das Root-Verzeichnis als Publish-Verzeichnis beibehalten

# Redirects f체r den Admin-Bereich
[[redirects]]
  from = "/admin/*"
  to = "/admin/index.html"
  status = 200

# Identity Settings
[template.environment]
  NETLIFY_IDENTITY_ENABLED = "true"

# Headers f체r bessere Sicherheit, aber mit den notwendigen Ausnahmen f체r CMS
[[headers]]
  for = "/admin/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "same-origin"
    # Weniger strenge CSP, die CMS-Funktionalit채t erlaubt
    Content-Security-Policy = "default-src 'self' https://unpkg.com https://identity.netlify.com; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://unpkg.com https://identity.netlify.com; style-src 'self' 'unsafe-inline' https://unpkg.com; img-src 'self' data: https://unpkg.com; font-src 'self' data: https://unpkg.com; connect-src 'self' https://api.netlify.com https://identity.netlify.com;"
