backend:
  name: git-gateway
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "seiteninhalte"
    label: "Seiteninhalte"
    files:
      - file: "index.html"
        label: "Landing Page"
        name: "landing"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Inhalt", name: "body", widget: "markdown" }
