backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "landing"
    label: "Landing Page"
    files:
      - file: "content/landing.md"
        label: "Landing Inhalt"
        name: "landing"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Slogan", name: "subtitle", widget: "string" }
          - { label: "Button-Text", name: "cta", widget: "string" }

  - name: "gallery"
    label: "Galerie"
    folder: "content/gallery"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Bildtitel", name: "title", widget: "string" }
      - { label: "Bild", name: "image", widget: "image" }

  - name: "about"
    label: "Über uns"
    files:
      - file: "content/about.md"
        label: "Über uns"
        name: "about"
        fields:
          - { label: "Titel", name: "title", widget: "string" }
          - { label: "Text", name: "body", widget: "markdown" }

  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Titel", name: "title", widget: "string" }
      - { label: "Inhalt", name: "body", widget: "markdown" }
