backend:
  name: github
  repo: 3Blin/CyberScouts-Website
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  # Kursangebote
  - name: "kurse"
    label: "Kursangebote"
    folder: "_kurse"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "kurs"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Bild", name: "image", widget: "image"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Preis", name: "price", widget: "number"}
      - {label: "Beschreibung", name: "description", widget: "text"}
      - {label: "Details", name: "body", widget: "markdown"}

  # Events/Veranstaltungen
  - name: "events"
    label: "Veranstaltungen"
    folder: "_events"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - {label: "Layout", name: "layout", widget: "hidden", default: "event"}
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Bild", name: "image", widget: "image"}
      - {label: "Datum", name: "date", widget: "datetime"}
      - {label: "Ort", name: "location", widget: "string"}
      - {label: "Beschreibung", name: "description", widget: "text"}
      - {label: "Details", name: "body", widget: "markdown"}

  # Team-Mitglieder
  - name: "team"
    label: "Team"
    folder: "_team"
    create: true
    fields:
      - {label: "Name", name: "title", widget: "string"}
      - {label: "Position", name: "position", widget: "string"}
      - {label: "Bild", name: "image", widget: "image"}
      - {label: "Über", name: "body", widget: "markdown"}

  # Seiten (für statische Inhalte)
  - name: "seiten"
    label: "Seiten"
    folder: "_seiten"
    create: true
    fields:
      - {label: "Titel", name: "title", widget: "string"}
      - {label: "Permalink", name: "permalink", widget: "string"}
      - {label: "Inhalt", name: "body", widget: "markdown"}

  # FAQ
  - name: "faq"
    label: "FAQ"
    folder: "_faq"
    create: true
    fields:
      - {label: "Frage", name: "title", widget: "string"}
      - {label: "Antwort", name: "body", widget: "markdown"}
